name: .NET Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # позволяет запускать вручную из вкладки Actions

jobs:
  run-dotnet-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # 1️ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ Устанавливаем .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # или 7.0.x, если используешь .NET 7

      # 3️ Восстанавливаем зависимости
      - name: Restore dependencies
        run: dotnet restore Project/TestWorkFlow/TestWorkFlow.csproj

      # 4️ Компилируем проект
      - name: Build project
        run: dotnet build Project/TestWorkFlow/TestWorkFlow.csproj --configuration Release --no-restore

      # 5️ Запускаем тесты
      - name: Run tests
        run: dotnet test Project/TestWorkFlow/TestWorkFlow.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      # 6️ Загружаем отчёт о тестах
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Project/TestWorkFlow/TestResults/
